"""Tests for `_rebuild_person_backlinks`.

Person pages used to be bare stubs — readers clicking `[[taher-saify-...]]`
from a topic landed on a page with only `email: ...` and nothing else,
no way back to the topic. This generator scans content pages for incoming
wikilinks and writes an "Appears in" section on every person page.
"""

from __future__ import annotations

from pathlib import Path

from src.wiki.landing import rebuild_landing_pages


def _write(path: Path, frontmatter: str, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"---\n{frontmatter}\n---\n\n{body}", encoding="utf-8")


class TestPersonBacklinks:
    def test_single_incoming_wikilink_creates_section(self, tmp_path: Path) -> None:
        _write(
            tmp_path / "people" / "taher-saify-indiamart-com.md",
            "title: Taher Saify\npage_type: person\nstatus: active\n"
            "email: taher.saify@indiamart.com\nsources: []\nrelated: []",
            "Email: taher.saify@indiamart.com\n",
        )
        _write(
            tmp_path / "topics" / "seo-rework.md",
            "title: SEO Rework\npage_type: topic\nstatus: active\n"
            "sources:\n- raw/x.md\nlast_compiled: '2026-04-16T00:00:00+00:00'",
            "Body.\n\n[[taher-saify-indiamart-com]] initiated the rework.\n",
        )

        rebuild_landing_pages(str(tmp_path))
        person_body = (tmp_path / "people" / "taher-saify-indiamart-com.md").read_text(
            encoding="utf-8"
        )
        assert "## Appears in" in person_body
        assert "[[seo-rework]] — SEO Rework" in person_body
        assert "generated by compiler" in person_body

    def test_multiple_categories_are_grouped(self, tmp_path: Path) -> None:
        _write(
            tmp_path / "people" / "amit.md",
            "title: Amit\npage_type: person\nsources: []",
            "stub body\n",
        )
        _write(
            tmp_path / "topics" / "topic-a.md",
            "title: Topic A\nsources:\n- raw/x.md",
            "[[amit]]\n",
        )
        _write(
            tmp_path / "systems" / "system-a.md",
            "title: System A\nsources:\n- raw/y.md",
            "[[amit]] owns this.\n",
        )

        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "amit.md").read_text(encoding="utf-8")
        assert "### Products & Platforms" in body
        assert "### Topics" in body
        topics_idx = body.index("### Topics")
        systems_idx = body.index("### Products & Platforms")
        # Categories sort alphabetically: systems < topics.
        assert systems_idx < topics_idx

    def test_dedup_multiple_mentions_same_page(self, tmp_path: Path) -> None:
        _write(
            tmp_path / "people" / "rucha.md",
            "title: Rucha\npage_type: person\nsources: []",
            "stub\n",
        )
        _write(
            tmp_path / "topics" / "seo.md",
            "title: SEO\nsources:\n- raw/x.md",
            "[[rucha]] led the QA pass.\n\nLater: [[rucha]] also reviewed.\n",
        )

        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "rucha.md").read_text(encoding="utf-8")
        assert body.count("[[seo]] — SEO") == 1

    def test_piped_and_slashed_wikilinks_both_match(self, tmp_path: Path) -> None:
        _write(
            tmp_path / "people" / "vikram.md",
            "title: Vikram\npage_type: person\nsources: []",
            "stub\n",
        )
        _write(
            tmp_path / "topics" / "a.md",
            "title: A\nsources:\n- raw/x.md",
            "[[vikram|Vikram V]] did the first pass.\n",
        )
        _write(
            tmp_path / "topics" / "b.md",
            "title: B\nsources:\n- raw/x.md",
            "Later work by [[people/vikram]].\n",
        )

        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "vikram.md").read_text(encoding="utf-8")
        assert "[[a]] — A" in body
        assert "[[b]] — B" in body

    def test_idempotent_second_run_no_duplication(self, tmp_path: Path) -> None:
        _write(
            tmp_path / "people" / "taher.md",
            "title: Taher\npage_type: person\nsources: []",
            "existing stub body\n",
        )
        _write(
            tmp_path / "topics" / "t.md",
            "title: T\nsources:\n- raw/x.md",
            "[[taher]] led work.\n",
        )

        rebuild_landing_pages(str(tmp_path))
        first = (tmp_path / "people" / "taher.md").read_text(encoding="utf-8")
        rebuild_landing_pages(str(tmp_path))
        second = (tmp_path / "people" / "taher.md").read_text(encoding="utf-8")
        assert first == second
        assert first.count("## Appears in") == 1

    def test_existing_body_above_section_preserved(self, tmp_path: Path) -> None:
        # Simulate a person page with real hand-written content above the
        # auto-generated section. Re-running must not touch that prose.
        seed = (
            "Email: mary@indiamart.com\n\n"
            "Mary is the SEO lead; hand-curated bio.\n\n"
            "## Appears in\n\n(stale content)\n\n<!-- generated by compiler; do not edit by hand -->\n"
        )
        _write(
            tmp_path / "people" / "mary.md",
            "title: Mary\npage_type: person\nsources: []",
            seed,
        )
        _write(
            tmp_path / "topics" / "seo.md",
            "title: SEO\nsources:\n- raw/x.md",
            "[[mary]] owns SEO.\n",
        )

        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "mary.md").read_text(encoding="utf-8")
        assert "Mary is the SEO lead; hand-curated bio." in body
        # Stale content should be gone.
        assert "(stale content)" not in body
        # Fresh section exists with the current backlink.
        assert "[[seo]] — SEO" in body

    def test_person_with_no_backlinks_gets_no_section(self, tmp_path: Path) -> None:
        _write(
            tmp_path / "people" / "loner.md",
            "title: Loner\npage_type: person\nsources: []",
            "stub body\n",
        )
        _write(
            tmp_path / "topics" / "unrelated.md",
            "title: Unrelated\nsources:\n- raw/x.md",
            "No mentions here.\n",
        )

        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "loner.md").read_text(encoding="utf-8")
        assert "## Appears in" not in body

    def test_decisions_category_display_name(self, tmp_path: Path) -> None:
        _write(
            tmp_path / "people" / "decider.md",
            "title: Decider\npage_type: person\nsources: []",
            "stub\n",
        )
        _write(
            tmp_path / "decisions" / "some-call.md",
            "title: Some Call\nsources:\n- raw/x.md",
            "Final call by [[decider]].\n",
        )
        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "decider.md").read_text(encoding="utf-8")
        assert "### Decisions" in body
        assert "### decisions" not in body

    def test_hand_written_appears_in_without_sentinel_preserved(self, tmp_path: Path) -> None:
        # Contributor hand-writes an "Appears in" section BEFORE the
        # generator ships. Next rebuild must not wipe it — the sentinel
        # comment is the discriminator for auto-generated vs hand-curated.
        seed = (
            "Email: handwritten@indiamart.com\n\n"
            "## Appears in\n\n- [[legacy-page]] — written by hand; no sentinel below.\n"
        )
        _write(
            tmp_path / "people" / "handwritten.md",
            "title: Handwritten\npage_type: person\nsources: []",
            seed,
        )
        _write(
            tmp_path / "topics" / "new.md",
            "title: New\nsources:\n- raw/x.md",
            "[[handwritten]] contributed here.\n",
        )

        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "handwritten.md").read_text(encoding="utf-8")
        # Hand-written line preserved (no sentinel → hands off).
        assert "written by hand; no sentinel below" in body
        assert "[[legacy-page]]" in body
        # No duplicate heading appended alongside the hand-written one.
        assert body.count("## Appears in") == 1
        # Generator stayed away entirely — no sentinel was added.
        assert "generated by compiler" not in body

    def test_stale_section_removed_when_mentions_all_gone(self, tmp_path: Path) -> None:
        seed = (
            "Email: old@indiamart.com\n\n"
            "## Appears in\n\n- [[gone]] — Gone\n\n<!-- generated by compiler; do not edit by hand -->\n"
        )
        _write(
            tmp_path / "people" / "old.md",
            "title: Old\npage_type: person\nsources: []",
            seed,
        )
        # No topics reference `old` at all.

        rebuild_landing_pages(str(tmp_path))
        body = (tmp_path / "people" / "old.md").read_text(encoding="utf-8")
        assert "## Appears in" not in body
        assert "- [[gone]]" not in body
