"""Person-page backlink rebuild — "Appears in" sections.

Pure-fs sweep: scans content pages (topics, systems, policies, etc.) for
`[[<slug>]]` wikilinks whose target lives in `wiki/people/`, then rewrites
the auto-generated "Appears in" section on each linked person page so
readers landing on a person see how they connect back to the content.

Extracted from the legacy `src/compile/compiler.py` in Phase 1A.1.
`src/compile/` was deleted in the 2026-04-29 refactor; callers import
`_rebuild_person_backlinks` / `_write_person_backlinks` directly from
`src.wiki.backlinks`.
"""

from __future__ import annotations

import re
from pathlib import Path

from src.utils import extract_body as _extract_body
from src.utils import extract_frontmatter as _extract_frontmatter
from src.utils import render_with_frontmatter as _render_with_frontmatter
from src.wiki.landing import _SECTION_TITLES
from src.wiki.pages import _atomic_write_text

# Source categories scanned for incoming wikilinks. Person/entity pages
# aren't scanned — they're the targets, not linkers. Legacy wiki/entities/
# is intentionally out: C1 migrated those to wiki/people/ and anything
# left is a stub.
_BACKLINK_SOURCE_CATEGORIES: tuple[str, ...] = (
    "topics",
    "systems",
    "policies",
    "decisions",
    "timelines",
    "conflicts",
    "domains",
)

# Captures `[[target]]` or `[[target|display]]`. Non-greedy on pipe so
# `[[a|b]][[c]]` is two links, not one.
_WIKILINK_RE = re.compile(r"\[\[([^\[\]|#]+?)(?:\|[^\[\]]*?)?(?:#[^\[\]]*?)?\]\]")

# Marker for the auto-generated backlinks section. Seeing it in a page's
# body tells the next rebuild where to splice — anything after the marker
# gets replaced, anything before is preserved so hand-written body
# content stays.
_BACKLINKS_HEADING = "## Appears in"
_BACKLINKS_FOOTER = "<!-- generated by compiler; do not edit by hand -->"


def _rebuild_person_backlinks(wiki_path: Path) -> int:
    """Append/refresh an "Appears in" section on every wiki/people page.

    Scans content pages (topics, systems, policies, decisions, glossary,
    timelines, conflicts, domains) for `[[<slug>]]` wikilinks whose
    target matches a slug in `wiki/people/`. For each person with ≥ 1
    incoming link, rewrites the body's auto-generated section to list
    the linking pages grouped by category.

    Idempotent: re-running produces identical output. The section is
    marked with a sentinel comment so manual-edited body content above
    it is preserved.

    Returns the number of person pages whose backlinks section was
    written (either created or updated).
    """
    people_dir = wiki_path / "people"
    if not people_dir.exists():
        return 0

    # Build person-slug → person-md-path index. Target set for link matching.
    person_pages: dict[str, Path] = {}
    for md in people_dir.glob("*.md"):
        if md.name == "index.md":
            continue
        person_pages[md.stem] = md
    if not person_pages:
        return 0

    # Scan source pages. Collect per-target list of (linker_slug, title, category).
    backlinks: dict[str, list[dict[str, str]]] = {slug: [] for slug in person_pages}
    for category in _BACKLINK_SOURCE_CATEGORIES:
        cat_dir = wiki_path / category
        if not cat_dir.exists():
            continue
        for md in cat_dir.glob("*.md"):
            if md.name == "index.md":
                continue
            try:
                content = md.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            fm = _extract_frontmatter(content)
            body = _extract_body(content)
            title = str(fm.get("title") or md.stem)
            seen_here: set[str] = set()
            for match in _WIKILINK_RE.finditer(body):
                target = match.group(1).strip()
                # Normalize `people/<slug>` → `<slug>` so either form matches.
                if "/" in target:
                    target = target.rsplit("/", 1)[-1]
                if target in person_pages and target not in seen_here:
                    seen_here.add(target)
                    backlinks[target].append(
                        {"slug": md.stem, "title": title, "category": category}
                    )

    # Deterministic order: category asc, then slug asc. Stable snapshot.
    for entries in backlinks.values():
        entries.sort(key=lambda e: (e["category"], e["slug"]))

    written = 0
    for slug, path in person_pages.items():
        entries = backlinks[slug]
        if _write_person_backlinks(path, entries):
            written += 1
    return written


def _write_person_backlinks(path: Path, entries: list[dict[str, str]]) -> bool:
    """Rewrite the backlinks section of ONE person page. Returns True if
    the file changed on disk.

    Preserves frontmatter and any body above the `## Appears in` heading.
    If the heading is absent, appends at the bottom. If `entries` is
    empty, removes any existing generated section so bare stubs don't
    carry a dangling header.
    """
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    fm = _extract_frontmatter(content)
    body = _extract_body(content)

    # Guard on the sentinel footer so a hand-written `## Appears in`
    # section (without the sentinel) is preserved — otherwise the
    # "NEVER remove history" invariant leaks. Three states:
    #   - has_generated (heading + sentinel): strip + rewrite
    #   - has_handwritten (heading but no sentinel): leave the page alone
    #   - neither: append the generated block fresh
    heading_idx = body.find(_BACKLINKS_HEADING)
    sentinel_idx = body.find(_BACKLINKS_FOOTER)
    has_generated = heading_idx != -1 and sentinel_idx != -1 and sentinel_idx > heading_idx
    has_handwritten = heading_idx != -1 and not has_generated

    if has_handwritten:
        # Hand-written section wins. Don't strip, don't append — a
        # second `## Appears in` underneath would duplicate the heading.
        return False

    if has_generated:
        body = body[:heading_idx].rstrip() + "\n"

    if entries:
        lines = ["", _BACKLINKS_HEADING, ""]
        current_category: str | None = None
        for entry in entries:
            if entry["category"] != current_category:
                current_category = entry["category"]
                lines.append(f"### {_SECTION_TITLES.get(current_category, current_category)}")
                lines.append("")
            lines.append(f"- [[{entry['slug']}]] — {entry['title']}")
        lines.append("")
        lines.append(_BACKLINKS_FOOTER)
        lines.append("")
        new_body = body.rstrip() + "\n" + "\n".join(lines)
    else:
        new_body = body

    new_content = _render_with_frontmatter(fm, new_body)
    if new_content == content:
        return False
    _atomic_write_text(path, new_content)
    return True
