"""Landing-page generators — home, changes, domain hubs, decision stubs.

Pure-fs generators for the wiki's landing surfaces. Includes:

* `update_wiki_index` — `wiki/compile-status.md` ops view + auto-stamp.
* `rebuild_landing_pages` — section-index regeneration entrypoint.
* `_generate_home` / `_generate_changes` — reader-facing home + changes feed.
* `_regenerate_domain_hubs` — `wiki/domains/<slug>.md` rebuild.
* `_regenerate_decision_stubs` — lazy `wiki/decisions/<slug>.md` stubs.

Extracted from the legacy `src/compile/compiler.py` and `src/compile/landing.py`
in Phase 1A.2. `src/compile/` was deleted in the 2026-04-29 refactor, so there
is no compatibility shim — callers (the post-batch coordinator, scripts) import
these names directly from `src.wiki.landing`.

Glossary removed 2026-04-24: the prior regex-based extractor produced
misleading definitions (`BL = "Monolith + Modular"`, `DAU = "January 8, 2026"`,
`CPC = "₹"`). No persona used the glossary, so the feature was dropped rather
than repaired. Reintroduce via an LLM pass if a real demand appears.
"""

from __future__ import annotations

import html
import re
from contextlib import suppress
from datetime import UTC
from datetime import datetime
from pathlib import Path
from typing import Any
from typing import cast
from zoneinfo import ZoneInfo

import structlog
import yaml
from langchain_core.tools import tool

from src.config import settings
from src.utils import extract_body as _extract_body
from src.utils import extract_frontmatter as _extract_frontmatter
from src.utils import render_with_frontmatter
from src.utils import render_with_frontmatter as _render_with_frontmatter
from src.wiki.domains import _DOMAIN_BY_SLUG
from src.wiki.domains import _DOMAINS
from src.wiki.domains import _assign_domains
from src.wiki.domains import _was_domain_inferred
from src.wiki.pages import _atomic_write_text
from src.wiki.pages import _first_paragraph
from src.wiki.pages import _iter_content_pages
from src.wiki.pages import _page_summary
from src.wiki.pages import _read_page
from src.wiki.pages import _replace_referenced_by

# `src.wiki.backlinks` imports `_SECTION_TITLES` from this module, so a
# top-level `from src.wiki.backlinks import _rebuild_person_backlinks`
# would create an import cycle (landing → backlinks → landing). Lazy-
# import inside `rebuild_landing_pages` instead. The cycle is purely
# import-time — at call time both modules are fully loaded.

logger = structlog.get_logger(__name__)
IST = ZoneInfo("Asia/Kolkata")


_GENERATED_MARKER = "<!-- generated by compiler; do not edit by hand -->"


# User-facing blurbs for the home-page domain cards. Keyed by slug so
# copy can evolve without touching `_DOMAINS` (which drives keyword
# matching); missing keys render as an empty line.
_DOMAIN_BLURBS: dict[str, str] = {
    "buyer-experience": "BuyMer, BuyLeads, search UX, and buyer-side WhatsApp.",
    "seller-experience": "AuditMate, seller dashboard, specs, compliance.",
    "marketplace-discovery": "MCAT, ISQ, photo search, ranking, categorization.",
    "platform-reliability": "GKE, Mesh PG, DB ops, API framework, performance.",
    "trust-safety": "KYC, GST, fraud, moderation, payment protection.",
    "ai-automation": "CrashAgent, WhatsApp 9696, autonomous assistants.",
    "growth-monetization": "Export, ads, affiliates, Google Merchant, tenders.",
    "engineering-productivity": "CI/CD, code quality, testing, dev tools.",
}

_UNCATEGORIZED_SLUG = "uncategorized"
_UNCATEGORIZED_TITLE = "Uncategorized"
_UNCATEGORIZED_BLURB = "Pages without an explicit `domain:` (or `domains:`) frontmatter."


_SECTION_BLURBS = {
    "topics": (
        "Projects, initiatives, rollouts, incidents, decisions, and "
        "migrations being discussed on the mailing list. If a page is "
        "mostly about **status and change**, it lives here."
    ),
    "systems": (
        "Durable products, platforms, tools, services, and mailing lists. "
        "If a page is mostly about **the thing itself**, it lives here."
    ),
    "people": (
        "Contributors and owners named on the mailing list. Stub pages "
        "with no cited sources are hidden from this view."
    ),
    "policies": (
        "Current rules, approval flows, guidelines, and procedures — "
        "including the supersession history when a policy has been replaced."
    ),
    "domains": (
        "Compiler-generated domain hubs — one per North-Star domain. "
        "Each lists the topics and systems tagged with that domain."
    ),
    "decisions": (
        "Explicit decisions made on the mailing list — rollouts, "
        "policy changes, supersession calls, architectural picks. "
        "Lazy-created and linked from topics."
    ),
}

_SECTION_TITLES = {
    "topics": "Topics",
    "systems": "Products & Platforms",
    "people": "People",
    "policies": "Policies",
    "domains": "Domains",
    "decisions": "Decisions",
}


_DECISION_LINK_RE = re.compile(r"\[\[decisions?/([A-Za-z0-9_\-]+)\]\]")


def _now_ist_iso() -> str:
    return datetime.now(IST).isoformat(timespec="seconds")


def _last_compiled_sort_key(value: object) -> float:
    """Return an absolute timestamp for sorting mixed-offset ISO strings."""
    if not value or value in ("stub", "stub-backfilled"):
        return 0.0
    if isinstance(value, datetime):
        dt = value if value.tzinfo is not None else value.replace(tzinfo=UTC)
        return dt.timestamp()
    text = str(value)
    try:
        dt = datetime.fromisoformat(text)
    except ValueError:
        return 0.0
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    return dt.timestamp()


def _relative_time(recency: float) -> str:
    dt = datetime.fromtimestamp(recency, tz=IST)
    iso = html.escape(dt.isoformat(timespec="seconds"), quote=True)
    fallback = dt.date().isoformat()
    return f'<time class="relative-time" datetime="{iso}">{fallback}</time>'


def _stacked_bar(parts: list[tuple[int, str]], total_max: int, width: int = 20) -> str:
    """Render a stacked ASCII bar. `parts` is [(count, glyph), ...] in stack order.

    Bar width is scaled relative to `total_max` (the busiest row in the chart)
    so a week with 1/3 the volume of the busiest renders as a 1/3-length bar.
    Less-busy rows produce a *shorter* bar (no trailing whitespace padding) —
    deliberate, so the eye reads volume and progress simultaneously: a tiny
    bar means "this week was small," a long bar with mostly `░` means "lots
    to do." Last segment absorbs rounding slack so totals always tile cleanly.
    """
    if total_max <= 0:
        return ""
    # Scale each segment to its share of the busiest row.
    cells: list[str] = []
    used = 0
    row_total = sum(c for c, _ in parts)
    bar_width = round(width * row_total / total_max) or (1 if row_total else 0)
    for i, (count, glyph) in enumerate(parts):
        if i == len(parts) - 1:
            # Last segment fills the remainder of the row's bar so rounding
            # error doesn't leave a one-cell gap.
            seg_width = bar_width - used
        else:
            seg_width = round(bar_width * count / row_total) if row_total else 0
        seg_width = max(0, seg_width)
        cells.append(glyph * seg_width)
        used += seg_width
    return "".join(cells)


def _compile_progress_block() -> list[str]:
    """Render a compile-progress section for `wiki/compile-status.md`.

    Pulls live state from Postgres and renders three views:

    1. Overall pie + headline counts.
    2. Threads per week — a thread is "fully done" when every email is in a
       terminal state (compiled or skipped), "in progress" when some are
       terminal and some aren't, "not started" when none are.
    3. Emails per week — broken out by state so trivially-skipped emails are
       visibly part of "done" rather than missing from the coverage bar.

    Bars are 3-tone stacked ASCII (`█` done · `▒` skipped/partial · `░`
    remaining). Mermaid is used only for the pie, which now renders thanks
    to the `pymdownx.superfences` mermaid fence wired up in `mkdocs.yml`.

    Fails open with an empty list if the DB is unreachable so index
    generation always succeeds.
    """
    try:
        from src.db import connect
    except ImportError:
        return []

    try:
        with connect() as conn:
            # connect() pins row_factory=dict_row; cast so mypy-strict
            # sees the real runtime shape (same shim as src/db/messages.py).
            state_rows = cast(
                "list[dict[str, Any]]",
                conn.execute(
                    "SELECT compile_state, count(*)::int AS n FROM messages GROUP BY 1"
                ).fetchall(),
            )
            email_weekly_rows = cast(
                "list[dict[str, Any]]",
                conn.execute(
                    """
                    SELECT date_trunc('week', date)::date AS week,
                           count(*)::int AS total,
                           count(*) FILTER (WHERE compile_state = 'compiled')::int AS compiled,
                           count(*) FILTER (WHERE compile_state = 'skipped')::int AS skipped,
                           count(*) FILTER (WHERE compile_state = 'pending')::int AS pending,
                           count(*) FILTER (WHERE compile_state = 'failed')::int AS failed,
                           count(*) FILTER (WHERE compile_state = 'claimed')::int AS claimed
                      FROM messages
                     WHERE date IS NOT NULL
                     GROUP BY 1
                     ORDER BY 1
                    """
                ).fetchall(),
            )
            # Threads per week: bin each thread by its earliest message date,
            # then classify by aggregate state across its members. Standalone
            # messages (NULL thread_id) count as their own thread.
            thread_weekly_rows = cast(
                "list[dict[str, Any]]",
                conn.execute(
                    """
                    WITH thread_state AS (
                        SELECT COALESCE(thread_id, message_id) AS group_key,
                               MIN(date) AS first_date,
                               bool_and(compile_state IN ('compiled', 'skipped')) AS all_terminal,
                               bool_or(compile_state IN ('compiled', 'skipped')) AS any_terminal
                          FROM messages
                         WHERE date IS NOT NULL
                         GROUP BY COALESCE(thread_id, message_id)
                    )
                    SELECT date_trunc('week', first_date)::date AS week,
                           count(*)::int AS total,
                           count(*) FILTER (WHERE all_terminal)::int AS done,
                           count(*) FILTER (WHERE any_terminal AND NOT all_terminal)::int AS partial,
                           count(*) FILTER (WHERE NOT any_terminal)::int AS not_started
                      FROM thread_state
                     GROUP BY 1
                     ORDER BY 1
                    """
                ).fetchall(),
            )
    except Exception:  # noqa: BLE001 — DB is best-effort for index rendering
        return []

    states = {r["compile_state"]: r["n"] for r in state_rows}
    total = sum(states.values())
    if total == 0:
        return []
    compiled = states.get("compiled", 0)
    pending = states.get("pending", 0)
    failed = states.get("failed", 0)
    claimed = states.get("claimed", 0)
    skipped = states.get("skipped", 0)
    terminal = compiled + skipped
    terminal_pct = (100 * terminal / total) if total else 0.0

    summary = f"{pending:,} pending, {failed:,} failed, {claimed:,} in-flight"
    if skipped:
        summary += f", {skipped:,} skipped (trivial-filter)"

    lines: list[str] = [
        "## Compile progress",
        "",
        (
            f"**{terminal:,} of {total:,} emails done** "
            f"({terminal_pct:.1f}% — {compiled:,} compiled + {skipped:,} skipped). "
            f"{summary}."
        ),
        "",
        "```mermaid",
        "pie showData title Compile state",
        f'    "compiled" : {compiled}',
        f'    "pending" : {pending}',
    ]
    if failed:
        lines.append(f'    "failed" : {failed}')
    if claimed:
        lines.append(f'    "in-flight" : {claimed}')
    if skipped:
        lines.append(f'    "skipped" : {skipped}')
    lines.extend(["```", ""])

    # ── Threads per week ──────────────────────────────────────────────
    if thread_weekly_rows:
        max_total = max(r["total"] for r in thread_weekly_rows) or 1
        lines.extend(
            [
                "### Threads per week (by earliest message)",
                "",
                "Bar legend: `█` fully done · `▒` partial · `░` not started.",
                "",
                "| Week starting | Threads | Done | Partial | Not started | Coverage |",
                "|---|---:|---:|---:|---:|---|",
            ]
        )
        for r in thread_weekly_rows:
            bar = _stacked_bar(
                [(r["done"], "█"), (r["partial"], "▒"), (r["not_started"], "░")],
                max_total,
            )
            lines.append(
                f"| {r['week']} | {r['total']} | {r['done']} | "
                f"{r['partial']} | {r['not_started']} | `{bar}` |"
            )
        lines.append("")

    # ── Emails per week ───────────────────────────────────────────────
    if email_weekly_rows:
        max_total = max(r["total"] for r in email_weekly_rows) or 1
        lines.extend(
            [
                "### Emails per week (by send date)",
                "",
                "Bar legend: `█` compiled · `▒` skipped · `░` pending/failed/in-flight.",
                "",
                "| Week starting | Emails | Compiled | Skipped | Pending | Failed | Coverage |",
                "|---|---:|---:|---:|---:|---:|---|",
            ]
        )
        for r in email_weekly_rows:
            remaining = r["pending"] + r["failed"] + r["claimed"]
            bar = _stacked_bar(
                [(r["compiled"], "█"), (r["skipped"], "▒"), (remaining, "░")],
                max_total,
            )
            lines.append(
                f"| {r['week']} | {r['total']} | {r['compiled']} | "
                f"{r['skipped']} | {r['pending']} | {r['failed']} | `{bar}` |"
            )
        lines.append("")

    return lines


@tool
def update_wiki_index(wiki_dir: str = "wiki") -> str:
    """Regenerate `wiki/compile-status.md` — internal ops view of the compile
    pipeline (counts, weekly coverage, per-category page listings).

    `/` is served by `wiki/index.md` (the North-Star 8-domain-card home,
    written by `_generate_home`). This function's output lives at
    `/compile-status/` so the owner can still inspect pipeline health
    without that view being the reader front door. Prior to 2026-04-24 this
    function wrote `wiki/index.md` directly; that stomped the reader home.

    Also auto-stamps `last_compiled` on any page missing the field, using the
    current real IST time. This guarantees every page has a timestamp without
    relying on the agent to call `stamp_page_compiled_at` for each one.

    Args:
        wiki_dir: Root wiki directory

    Returns:
        Summary: pages indexed + pages auto-stamped
    """
    wiki_path = Path(wiki_dir)
    if not wiki_path.exists():
        return f"ERROR: wiki directory not found: {wiki_dir}"

    categories: dict[str, list[str]] = {
        "policies": [],
        "topics": [],
        "entities": [],
        "systems": [],
        "timelines": [],
        "conflicts": [],
    }
    stamped = 0
    now_iso = _now_ist_iso()

    for category in categories:
        cat_dir = wiki_path / category
        if not cat_dir.exists():
            continue
        for md_file in sorted(cat_dir.glob("*.md")):
            try:
                content = md_file.read_text(encoding="utf-8")
                fm = _extract_frontmatter(content)
                # Auto-stamp only if the frontmatter looks complete enough.
                # A broken frontmatter (e.g., only `last_compiled` present) means
                # the agent's edit_file mangled the page — don't overwrite it,
                # or we'll destroy what's left.
                has_real_fields = "title" in fm or "page_type" in fm
                if "last_compiled" not in fm and has_real_fields:
                    fm["last_compiled"] = now_iso
                    fm.setdefault("updated_by", settings.llm_model)
                    fm["update_count"] = int(fm.get("update_count") or 0) + 1
                    body = _extract_body(content)
                    md_file.write_text(_render_with_frontmatter(fm, body), encoding="utf-8")
                    stamped += 1
                title = fm.get("title", md_file.stem)
                status = fm.get("status", "current")
                name = md_file.stem
                entry = f"- [[{name}]] — {title}"
                if status != "current":
                    entry += f" *({status})*"
                categories[category].append(entry)
            except (yaml.YAMLError, UnicodeDecodeError):
                continue

    lines = [
        "# Compile status",
        "",
        "Internal pipeline view — counts, weekly coverage, and the full page",
        "catalog. For the reader-facing home, see [/]( ./).",
        "",
        f"Last updated: {now_iso}",
        "",
    ]
    lines.extend(_compile_progress_block())

    total = 0
    cat_blocks: list[str] = []
    for cat_name, entries in categories.items():
        if entries:
            cat_blocks.append(f"## {cat_name.title()} ({len(entries)})")
            cat_blocks.extend(entries)
            cat_blocks.append("")
            total += len(entries)

    lines.insert(5, f"Total pages: {total}")
    lines.insert(6, "")
    lines.extend(cat_blocks)

    index_path = wiki_path / "compile-status.md"
    index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    # Retire the legacy `wiki/index.md` written by this function before
    # 2026-04-24 — `_generate_home` now owns that path. Safe to unlink
    # because `_generate_home` (called later in the landing-surfaces
    # phase) will recreate index.md with the reader-facing home content.
    legacy_index = wiki_path / "index.md"
    if legacy_index.exists():
        with suppress(OSError):
            legacy_index.unlink()

    # Rebuild reader-facing landing pages (home.md + section indexes) so the
    # deployed site shows real page listings instead of the hand-written
    # "(Placeholder — comes in a later PR)" stubs. Deterministic — no LLM in
    # this path — so it's safe to run every compile cycle.
    landing_summary = rebuild_landing_pages(wiki_dir)

    return (
        f"updated index: {total} pages across "
        f"{sum(1 for v in categories.values() if v)} categories; "
        f"auto-stamped {stamped} pages with last_compiled; "
        f"{landing_summary}"
    )


def rebuild_landing_pages(wiki_dir: str = "wiki") -> str:
    """Regenerate home.md + 4 section index pages as real listings.

    Replaces the hardcoded "(Placeholder — comes in a later PR)" stubs
    with full page listings sorted by `last_compiled` desc. Entity and
    system pages with `sources: []` are hidden (they're ghost pages left
    over from the create_entity evidence-gate workflow).

    Also rebuilds the "## Appears in" backlinks section on every person
    page — readers landing on a person page (often via wikilink from a
    topic) otherwise see a bare stub with no way back to the content
    they came from.

    This is a pure coordinator function — no LLM — so it runs on every
    compile cycle via `update_wiki_index` (the shared entrypoint used
    by compile_all, compile_parallel, and watch_and_compile).

    Returns a one-line summary for the CLI log.
    """
    wiki_path = Path(wiki_dir)
    if not wiki_path.exists():
        return f"landing rebuild skipped: wiki dir not found ({wiki_dir})"

    now_iso = _now_ist_iso()
    sections: dict[str, list[dict[str, Any]]] = {}
    for category in _SECTION_TITLES:
        cat_dir = wiki_path / category
        pages: list[dict[str, Any]] = []
        if cat_dir.exists():
            for md_file in cat_dir.glob("*.md"):
                if md_file.name == "index.md":
                    continue
                summary = _page_summary(md_file)
                if summary is None:
                    continue
                # Hide ghost system pages (auto-stub gate is closed but
                # legacy ones remain). People pages are intentionally
                # provenance-light — they're cited via incoming wikilinks
                # from topics/systems, not via per-message `sources:` —
                # so filtering them by the same stub rule would zero out
                # the people index. Status filter handles superseded.
                if category == "systems" and summary["is_stub"]:
                    continue
                pages.append(summary)
        pages.sort(
            key=lambda p: (_last_compiled_sort_key(p["last_compiled"]), p["title"]),
            reverse=True,
        )
        sections[category] = pages

    for category, pages in sections.items():
        _write_section_index(wiki_path, category, pages, now_iso)

    # home.md retired 2026-04-24 — `_generate_home` (called later in
    # `_regenerate_landing_surfaces`) owns the reader-facing front door
    # at `wiki/index.md` with the 8-domain card layout. Keeping a
    # `_write_home` call here would just write a file that the next
    # step deletes.
    from src.wiki.backlinks import _rebuild_person_backlinks

    backlinks_count = _rebuild_person_backlinks(wiki_path)

    totals = ", ".join(f"{k}={len(v)}" for k, v in sections.items())
    return f"rebuilt landing pages ({totals}, person_backlinks={backlinks_count})"


def _write_section_index(
    wiki_path: Path, category: str, pages: list[dict[str, Any]], now_iso: str
) -> None:
    """Write `<category>/index.md` as a real listing."""
    title = _SECTION_TITLES[category]
    blurb = _SECTION_BLURBS[category]
    lines = [f"# {title}", "", blurb, ""]
    if pages:
        lines.extend([f"**{len(pages)} pages**, most recently compiled first.", ""])
        for page in pages:
            # Canonical status values — `active` (new) and `current` (legacy)
            # both mean "live page, no suffix". Everything else (`superseded`,
            # `archived`, `contested`) gets a suffix so readers see it.
            status_suffix = (
                "" if page["status"] in ("active", "current") else f" *({page['status']})*"
            )
            entry = f"- [[{page['slug']}]] — {page['title']}{status_suffix}"
            lines.append(entry)
            if page["summary"]:
                lines.append(f"  <br>{page['summary']}")
    else:
        lines.append("*No pages compiled yet.*")
    lines.append("")

    fm = {
        "title": title,
        "page_type": "index",
        "status": "active",
        "last_compiled": now_iso,
    }
    _atomic_write_text(
        wiki_path / category / "index.md",
        _render_with_frontmatter(fm, "\n".join(lines)),
    )


# === North-Star landing generators ===
#
# These surface the 8 fixed domain hubs, glossary, home, changes, and lazy
# decision stubs called out in docs/NORTH-STAR.md. All are pure coordinator
# functions (no LLM) called after `rebuild_landing_pages` so the deployed
# site reflects the concept-wiki ontology even before per-page frontmatter
# catches up.


def _regenerate_domain_hubs(wiki_dir: Path) -> list[Path]:
    """Emit `wiki/domains/<slug>.md` for each of the 8 fixed domains.

    Always writes all 8 — an empty domain still gets a page so the home
    page's domain-card grid resolves every link. Idempotent: same corpus
    produces byte-identical output.
    """
    buckets: dict[str, dict[str, list[tuple[str, str]]]] = {
        slug: {"topics": [], "systems": []} for slug, _t, _k in _DOMAINS
    }
    inferred_count = 0

    for md_file in _iter_content_pages(wiki_dir):
        read = _read_page(md_file)
        if read is None:
            continue
        fm, body = read
        category = md_file.parent.name
        slugs = _assign_domains(fm, body, md_file.stem)
        if not slugs:
            continue
        if _was_domain_inferred(fm):
            inferred_count += 1
        entry = (md_file.stem, _first_paragraph(body))
        for slug in slugs:
            buckets[slug][category].append(entry)

    if inferred_count:
        # Single summary log per regen pass — replaces the per-page warning
        # that fired once per bucket lookup (v10-U3 followup P2, #191).
        logger.info(
            "domain-hub-inferred-from-keyword-summary",
            pages=inferred_count,
        )

    domains_dir = wiki_dir / "domains"
    written: list[Path] = []
    for slug, title, _keywords in _DOMAINS:
        bucket = buckets[slug]
        for category_pages in bucket.values():
            category_pages.sort(key=lambda e: e[0])

        lines = [f"# {title}", "", "## Topics", ""]
        topics = bucket["topics"]
        if topics:
            for stem, summary in topics:
                suffix = f" — {summary}" if summary else ""
                lines.append(f"- [[topics/{stem}]]{suffix}")
        else:
            lines.append("*No topics yet.*")
        lines.extend(["", "## Systems", ""])
        systems = bucket["systems"]
        if systems:
            for stem, summary in systems:
                suffix = f" — {summary}" if summary else ""
                lines.append(f"- [[systems/{stem}]]{suffix}")
        else:
            lines.append("*No systems yet.*")
        lines.extend(["", _GENERATED_MARKER, ""])

        fm = {
            "title": title,
            "page_type": "domain",
            "status": "active",
            "slug": f"domains/{slug}",
        }
        path = domains_dir / f"{slug}.md"
        _atomic_write_text(path, _render_with_frontmatter(fm, "\n".join(lines)))
        logger.info(
            "generated",
            kind="domain-hub",
            slug=slug,
            topics=len(topics),
            systems=len(systems),
        )
        written.append(path)
    return written


def _regenerate_decision_stubs(wiki_dir: Path) -> list[Path]:
    """Lazy-create `wiki/decisions/<slug>.md` stubs for every wikilink target.

    Idempotent:
    - Never overwrites an existing decision page's body — they may be
      human-authored or future-compiled with real content.
    - Always rewrites the "Referenced by" block so links stay fresh as
      topics are added/removed.
    """
    backrefs: dict[str, list[str]] = {}
    for md_file in _iter_content_pages(wiki_dir):
        try:
            body = md_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for match in _DECISION_LINK_RE.finditer(body):
            slug = match.group(1)
            link = f"{md_file.parent.name}/{md_file.stem}"
            slot = backrefs.setdefault(slug, [])
            if link not in slot:
                slot.append(link)

    decisions_dir = wiki_dir / "decisions"
    written: list[Path] = []
    for slug, refs in backrefs.items():
        path = decisions_dir / f"{slug}.md"
        title = slug.replace("-", " ").replace("_", " ").strip().title()
        refs_sorted = sorted(refs)

        existing = _read_page(path) if path.exists() else None
        if existing is None:
            lines = [
                f"# {title}",
                "",
                "<TODO: enrich from referencing topic(s)>",
                "",
                "## Referenced by",
                "",
            ]
            lines.extend(f"- [[{r}]]" for r in refs_sorted)
            lines.extend(["", _GENERATED_MARKER, ""])
            fm = {
                "title": title,
                "page_type": "decision",
                "status": "active",
                "slug": f"decisions/{slug}",
            }
            _atomic_write_text(path, _render_with_frontmatter(fm, "\n".join(lines)))
            logger.info("generated", kind="decision-stub", slug=slug, refs=len(refs_sorted))
        else:
            fm, body = existing
            new_body = _replace_referenced_by(body, refs_sorted)
            if new_body != body:
                _atomic_write_text(path, _render_with_frontmatter(fm, new_body))
                logger.info(
                    "updated",
                    kind="decision-stub-refs",
                    slug=slug,
                    refs=len(refs_sorted),
                )
        written.append(path)
    return written


def _recent_page_entries(
    buckets: dict[str, list[tuple[Path, float]]],
    limit: int = 10,
) -> list[tuple[Path, float]]:
    """Return the `limit` most recently modified topic+system pages.

    Reads from the already-computed `buckets` (as produced by
    `_bucket_pages_by_domain`) so "Recent changes" and each domain
    card's top-3 agree on ordering without a second disk traversal.
    Pages carry the same `_page_recency_key` the buckets use, so the
    Recent Changes section surfaces the most recently touched page
    regardless of which domain it lives in.
    """
    seen: set[Path] = set()
    merged: list[tuple[Path, float]] = []
    for entries in buckets.values():
        for md_file, recency in entries:
            if md_file in seen:
                continue
            seen.add(md_file)
            merged.append((md_file, recency))
    merged.sort(key=lambda p: p[1], reverse=True)
    return merged[:limit]


def _page_recency_key(fm: dict[str, Any], md_file: Path) -> float:
    """Return a sortable recency timestamp for a wiki page.

    Prefers the frontmatter `last_compiled` ISO string (what the
    coordinator stamps via `_stamp_recently_modified_pages`). Falls back
    to filesystem mtime so manually-edited pages still rank. On parse
    failure, returns 0.0 so bad frontmatter buckets to the bottom.
    """
    raw = fm.get("last_compiled")
    if isinstance(raw, str):
        ts = _last_compiled_sort_key(raw)
        if ts:
            return ts
    elif isinstance(raw, datetime):
        return _last_compiled_sort_key(raw)
    try:
        return md_file.stat().st_mtime
    except OSError:
        return 0.0


def _bucket_pages_by_domain(
    wiki_dir: Path,
) -> dict[str, list[tuple[Path, float]]]:
    """Group topic + system pages by assigned domain slug.

    Multi-domain pages (via `domains:` list, `tags:` with multiple
    domain slugs, or future extensions) appear in every matching
    bucket. Pages without any assignable domain land in
    `_UNCATEGORIZED_SLUG` so readers still find them. Returns
    `{domain_slug: [(md_file, recency_ts), ...]}` with entries sorted
    newest-first per bucket.
    """
    buckets: dict[str, list[tuple[Path, float]]] = {slug: [] for slug in _DOMAIN_BY_SLUG}
    buckets[_UNCATEGORIZED_SLUG] = []

    for md_file in _iter_content_pages(wiki_dir):
        read = _read_page(md_file)
        if read is None:
            continue
        fm, body = read
        recency = _page_recency_key(fm, md_file)
        slugs = _assign_domains(fm, body, md_file.stem)
        if not slugs:
            buckets[_UNCATEGORIZED_SLUG].append((md_file, recency))
            continue
        # _assign_domains only returns slugs validated against
        # _DOMAIN_BY_SLUG, so every slug here is a bucket key.
        for slug in slugs:
            buckets[slug].append((md_file, recency))

    for entries in buckets.values():
        entries.sort(key=lambda e: e[1], reverse=True)
    return buckets


def _render_domain_card(
    slug: str,
    title: str,
    blurb: str,
    entries: list[tuple[Path, float]],
    top_n: int = 3,
    *,
    linked: bool = True,
) -> list[str]:
    """Render one domain card as markdown lines.

    Cards always emit — an empty domain still gets a header so the home
    page reliably shows all 8 (or 9 with Uncategorized) sections. Each
    entry renders the page slug + the date portion of its recency
    timestamp; empty domains show a single italic placeholder.

    `linked=False` emits a plain `## <title>` header (no `domains/<slug>.md`
    hyperlink). Used for the Uncategorized bucket, which has no hub page —
    a link there would 404 in the viewer.
    """
    header = f"## [{title}](domains/{slug}.md)" if linked else f"## {title}"
    lines = [
        header,
        "",
        blurb,
        "",
        "**Top pages**:",
    ]
    if not entries:
        lines.append("- *No pages yet.*")
    else:
        for md_file, recency in entries[:top_n]:
            category = md_file.parent.name
            stamp = _relative_time(recency)
            lines.append(f"- [[{category}/{md_file.stem}]] — updated {stamp}")
    total = len(entries)
    noun = "page" if total == 1 else "pages"
    lines.extend(["", f"<small>{total} {noun} total</small>", ""])
    return lines


def _generate_home(wiki_dir: Path) -> Path:
    """Overwrite `wiki/index.md` with the North-Star 8-domain card layout.

    This is the page MkDocs serves at `/` (by default, `index.md` claims
    the site root). One card per canonical domain plus an "Uncategorized"
    card for pages without `domain:` / `domains:` frontmatter. Cards show
    the domain blurb, the 3 most-recently-compiled pages (by
    `last_compiled` DESC, falling back to file mtime), and a total count.
    Runs after `_regenerate_domain_hubs` so `domains/<slug>.md` already
    exists for the header links.

    Self-cleans any legacy `wiki/home.md` (the pre-2026-04-24 output path
    of this generator) so the old layout doesn't linger at `/home/` in
    the deployed viewer.
    """
    buckets = _bucket_pages_by_domain(wiki_dir)

    lines = [
        "# Email Knowledge Base — IndiaMART",
        "",
        "A compiled wikipedia derived from our mailing lists. Pages are",
        "about *things* (products, systems, initiatives, decisions), not",
        "*events* (threads, emails).",
        "",
        "Jump to [Changes](changes.md) for recent page activity.",
        "",
        "## Explore by domain",
        "",
    ]
    for slug, title, _keywords in _DOMAINS:
        blurb = _DOMAIN_BLURBS.get(slug, "")
        lines.extend(_render_domain_card(slug, title, blurb, buckets.get(slug, [])))

    uncategorized = buckets.get(_UNCATEGORIZED_SLUG, [])
    if uncategorized:
        lines.extend(
            _render_domain_card(
                _UNCATEGORIZED_SLUG,
                _UNCATEGORIZED_TITLE,
                _UNCATEGORIZED_BLURB,
                uncategorized,
                linked=False,
            )
        )

    recent = _recent_page_entries(buckets, limit=10)
    lines.extend(["## Recent changes", ""])
    if recent:
        for md_file, mtime in recent:
            category = md_file.parent.name
            stamp = _relative_time(mtime)
            lines.append(f"- {stamp} — [[{category}/{md_file.stem}]]")
    else:
        lines.append("*No pages compiled yet.*")

    lines.extend(["", _GENERATED_MARKER, ""])

    fm = {"title": "Home", "page_type": "home", "status": "active"}
    path = wiki_dir / "index.md"
    _atomic_write_text(path, render_with_frontmatter(fm, "\n".join(lines)))
    # Retire the legacy path so MkDocs doesn't render a stale `/home/`.
    legacy_home = wiki_dir / "home.md"
    if legacy_home.exists():
        try:
            legacy_home.unlink()
        except OSError as exc:
            logger.warning("legacy-home-unlink-failed", error=str(exc))
    populated_domains = sum(1 for slug, _t, _k in _DOMAINS if buckets.get(slug))
    logger.info(
        "generated",
        kind="home",
        recent_count=len(recent),
        populated_domains=populated_domains,
        uncategorized=len(uncategorized),
    )
    return path


def _generate_changes(wiki_dir: Path, db_conn: Any | None = None) -> Path:
    """Emit `wiki/changes.md` — recent wiki-page activity (not compile logs).

    Spec (docs/NORTH-STAR.md § "Changes") calls for product activity — what
    pages grew or changed recently — rendered as a chronological feed a
    reader can scan. The previous implementation emitted Postgres
    compile_attempts rows with LLM model names and outcomes, which surfaces
    as "12:13 UTC — failed (qwen/qwen3.5-122b-a10b)" on the reader-facing
    `/changes/` — useless for anyone not owning the compile pipeline.

    New behavior: a flat, recency-ordered list of the 60 most-recently-updated
    topic/system/policy pages — each line "Updated <relative-time> — [[page]]".
    The browser-side `<time class="relative-time">` JS already encodes recency,
    so day H2 grouping was redundant chrome that fragmented the feed.
    `db_conn` is ignored — kept in the signature for backward compatibility
    with existing callers; compile-attempt history now belongs on an
    internal ops page, not here.
    """
    buckets = _bucket_pages_by_domain(wiki_dir)
    recent = _recent_page_entries(buckets, limit=60)

    lines = ["# Changes", ""]
    if not recent:
        lines.append("*No recent activity.*")
    else:
        lines.extend(
            [
                "Most-recently-updated pages across the wiki. See each page for",
                "the underlying edit history and source threads.",
                "",
            ]
        )
        for md_file, recency in recent:
            category = md_file.parent.name
            lines.append(
                f"- Updated {_relative_time(recency)} — [[{category}/{md_file.stem}]]"
            )
        lines.append("")

    lines.extend([_GENERATED_MARKER, ""])

    fm = {"title": "Changes", "page_type": "changes", "status": "active"}
    path = wiki_dir / "changes.md"
    _atomic_write_text(path, render_with_frontmatter(fm, "\n".join(lines)))
    logger.info("generated", kind="changes", pages=len(recent))
    return path
